config/routes.rb
Rails.application.routes.draw do

  authenticated do
    root to: 'entries#index', as: :authenticated
  end

  root 'home#index'
  get '/home' => 'home#index'
  get '/about' => 'home#about'
  get '/contact' => 'home#contact'

  devise_for :users

  resources :entries
  resources :categories, param: :name

  post "/scraper" => "scrapers#create"
end

app/models/entry.rb
class Entry < ActiveRecord::Base
	has_many :categorizings
	has_many :categories, through: :categorizings
	default_scope { order('date') }
	validates_presence_of :title, :date, :location, :body
	validates_uniqueness_of :title
	validate :end_date_after_start
	after_destroy :remove_empty_categories
	belongs_to :user

	def end_date_after_start
		if end_date.present? && (end_date < date)
			errors.add(:end_date, "end date must come after start date")
		end
	end

	def remove_empty_categories
		categories.each do |category|
			category.destroy if category.entries.empty?
		end
	end

	def category_list
		categories.join(", ")
	end

	def category_list=(categories_string)
		category_names = categories_string.split(",").collect {|s| s.strip}.uniq
		new_or_found_categories = category_names.collect {|name| Category.find_or_create_by(name: name) }
		self.categories = new_or_found_categories
	end

	def self.keyword_search(search)
		if search
			where('LOWER(title) LIKE ? OR LOWER(body) LIKE ?', "%#{search.downcase}%", "%#{search.downcase}%") | joins(:categories).where('LOWER(categories.name) LIKE ?', "%#{search.downcase}%")
		else
			Entry.all
		end
	end
 
	def self.date_search(start_date, end_date)
		
		# Default dates if any field left blank
		start_month = 1
		start_day = 1
		if Entry.count != 0
			start_year = Entry.first.date.year
			end_year = Entry.last.date.year
		else
			start_year = 1000
			end_year = Date.today.year
		end
		end_month = 12
		end_day = 31

		# Prevent search completing until year filled out
		if start_date && end_date
			if start_date["(1i)"].length == 4
				start_year = start_date["(1i)"].to_i
				if start_date["(2i)"] != ""
					start_month = start_date["(2i)"].to_i
				end
				if start_date["(3i)"] != ""
					start_day = start_date["(3i)"].to_i
				end
			end

			if end_date["(1i)"].length == 4
				end_year = end_date["(1i)"].to_i
				if end_date["(2i)"] != ""
					end_month = end_date["(2i)"].to_i
				end
				if end_date["(3i)"] != ""
					end_day = end_date["(3i)"].to_i
				end
			end
		end

		date1 = Date.new start_year, start_month, start_day rescue nil
		date2 = Date.new end_year, end_month, end_day rescue nil

		where('date BETWEEN ? AND ?', "#{date1}", "#{date2}")
	end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
	respond_to :html, :js, :json
	before_filter :no_footer

	def index
		@grey_bg = true
		if params[:keyword_search]
			@entries = Entry.keyword_search(params[:keyword_search])
		else
			@entries = Entry.date_search(params[:start_date], params[:end_date])
		end

		# If search returns no results, create temporary entry telling user no entries were found 
		if @entries == []
			Struct.new("Entry", :title, :date, :location, :body, :id, :user)
			@error_entry = Struct::Entry.new("Sorry, that search didn't turn up any events!", Date.today, "limbo", "Try again with another keyword or date range.", -1, nil)
			@entries = [@error_entry]
		end

		@entry = Entry.new
 	end

	def show
		redirect_to entries_path
	end

	def new
		@entry = Entry.new
	end

	def create
		@entry = current_user.entries.build(entry_params)
		respond_to do |format|
			if @entry.save
				assign_end_date(@entry)
				@entries = Entry.all
				flash[:notice] = "'#{@entry.title}' created!"
				format.html {redirect_to entries_path }
				format.js
			else
				format.html { render :new }
				format.js
			end
		end		
	end

	def destroy
		@entry = Entry.find(params[:id])
		if @entry.destroy
			@entries = Entry.all
			flash[:notice] = "'#{@entry.title}' deleted"
			redirect_to entries_path
		else
			flash[:error] = "Sorry, there was a problem deleting the event."
			redirect_to entries_path
		end
	end

	def edit
		@entry = Entry.find(params[:id])
	end

	def update
		@entry = Entry.find(params[:id])
		respond_to do |format|
			if @entry.update(entry_params)
				assign_end_date(@entry)
				@entries = Entry.all
				flash[:notice] = "'#{@entry.title}' updated!"
				format.html {redirect_to entries_path }
				format.js
			else
				format.html { render :edit }
				format.js
			end
		end
	end

	private

	def entry_params
		params.require(:entry).permit(:title, :date, :end_date, :location, :body, :category_list, :url)
	end

	def no_footer
		@no_footer = true
	end

	def assign_end_date(entry)
		if entry.end_date == nil
			date = entry.date
			entry.update_attributes(end_date: date)
		end
	end

end

app/helpers/entries_helper.rb
module EntriesHelper

  def current_date_val(num)
    unless num == nil
      sprintf('%02i', num)
    end
  end

end

app/views/entries/_buttons.html.erb
<% if current_user %><div class='icons'><a href='entries/<%= entry.id %>/edit' action='edit' controller='entries' id='<%= entry.id %>' data-remote='true' data-toggle='modal' data-target='#entry_modal' data-dismiss='modal'  >✐</a><% if entry.user == current_user %><a href='/entries/<%= entry.id %>' action='destroy' controller='entries' id='<%= entry.id %>' data-method='delete' data-confirm='Are you sure?' >✖</a><% end %></div><br/><% end %>

app/views/entries/_entry.html.erb
<div class="<%= cycle('left-entry all_entries','right-entry all_entries') %>">
  
  <strong class=""><%= link_to entry.title, entry_path(entry), "data-toggle" => "modal", 'data-target' => "#show_modal", remote: :true %></strong><br>
  <em><%= entry.date.strftime("%B %e, %Y") %></em>
  <div><%= entry.body %></div>
  
  <div><%= render partial: 'entries/buttons', locals: { entry: entry } %></div>
  
</div>

app/views/entries/_form.html.erb
<%= form_for entry, remote: :true do |f| %>

  <p>
    <%= f.text_field :url, class: "form-field url-field", placeholder: "Enter URL of event" %>
  </p>

  <div class="scraper-loading" style="display: none"><%= image_tag("loading-dots.gif", height: "5") %></div>

  <p>
  	<button type="button" class="cancel-button button" id="scrape-button" >Scrape</button> <span class="question-mark" data-toggle="tooltip" data-placement="right" title="Get the title, a summary, date, and categories straight from the URL!">?</span>
  </p>

  <p>
    <%= f.label :title, 'What' %><br>
    <%= f.text_field :title, class: "form-field #{error_border(entry.errors[:title])}", placeholder: 'What happened?' %>
    <%= error_message(entry.errors[:title], 'title') %>
  </p>
  
  <p>
    <%= f.label :date, 'When' %><br/>
    <div id="start_date" class="datefield <%= error_border(entry.errors[:date]) %>">
      <input id="start_month" class="date-field" name="entry[date(2i)]" maxlength="2" placeholder="MM" value="<%= current_date_val(entry.date.try(:month)) %>" data-autotab-format="number"/> /
      <input id="start_day" class="date-field" name="entry[date(3i)]" maxlength="2" placeholder="DD" value="<%= current_date_val(entry.date.try(:day)) %>" data-autotab-format="number" /> /
      <input id="start_year" class="date-field" name="entry[date(1i)]" maxlength="4" placeholder="YYYY" value="<%= current_date_val(entry.date.try(:year)) %>" data-autotab-format="number"/>
    </div> <span class="date-divide">-</span>

    <div id="end_date" class="datefield <%= error_border(entry.errors[:end_date]) %>">
      <input id="end_month" class="date-field" name="entry[end_date(2i)]" maxlength="2" placeholder="MM" value="<%= current_date_val(entry.end_date.try(:month)) %>" data-autotab-format="number"/> /
      <input id="end_day" class="date-field" name="entry[end_date(3i)]" maxlength="2" placeholder="DD" value="<%= current_date_val(entry.end_date.try(:day)) %>" data-autotab-format="number" /> /
      <input id="end_year" class="date-field" name="entry[end_date(1i)]" maxlength="4" placeholder="YYYY" value="<%= current_date_val(entry.end_date.try(:year)) %>" data-autotab-format="number"/>
    </div>
    <br/>
    <span class="month-errors"></span><span class="day-errors"></span><span class="year-errors"></span>
    <%= error_message(entry.errors[:date], 'date') %>
    <%= error_message(entry.errors[:end_date], 'end_date') %>
  </p>

  <p>
    <%= f.label :location, 'Where' %><br>
    <%= f.text_field :location, class: "form-field #{error_border(entry.errors[:location])}", placeholder: 'Where did it happen?' %>
    <%= error_message(entry.errors[:location], 'location') %>
  </p>

  <p>
    <%= f.label :body, 'How' %><br>
    <%= f.text_area :body, class: "form-body form-field #{error_border(entry.errors[:body])}", placeholder: 'How did it happen?' %>
    <%= error_message(entry.errors[:body], 'body') %>
  </p>

  <p>
    <%= f.label :category_list, 'Categories' %><br>
    <%= f.text_field :category_list, id: "select2field", style: "width:100%" %>
  </p>
  
  <div class="modal-footer">
    <button type="button" class="cancel-button button" data-dismiss="modal">Close</button>
    <%= f.submit 'Save', class: 'button' %>
  </div>

<% end %>

<script>

$(document).ready(function() {
  $("#select2field").select2({
    minimumInputLength: 1,
    tags: <%= raw Category.pluck(:name) %>,
    tokenSeparators: [","]
   });

  $('[data-toggle="tooltip"]').tooltip();

});



</script>

app/views/entries/_form2.html.erb
<%= form_for entry do |f| %>

  <p>
    <%= f.text_field :url, class: "form-field url-field", placeholder: "Enter URL of event" %>
  </p>

  <div class="scraper-loading" style="display: none"><%= image_tag("loading-dots.gif", height: "5") %></div>

  <p>
    <button type="button" class="cancel-button button" id="scrape-button">Scrape</button> <span class="question-mark" data-toggle="tooltip" data-placement="right" title="Get the title, a summary, date, and categories straight from the URL!">?</span>
  </p>

  <p>
    <%= f.label :title, 'What' %><br>
    <%= f.text_field :title, class: "form-field #{error_border(entry.errors[:title])}", placeholder: 'What happened?' %>
    <%= error_message(entry.errors[:title], 'title') %>
  </p>
  
  <p>
    <%= f.label :date, 'When' %><br/>
    <div id="start_date" class="datefield <%= error_border(entry.errors[:date]) %>">
      <input id="start_month" class="date-field" name="entry[date(2i)]" maxlength="2" placeholder="MM" value="<%= current_date_val(entry.date.try(:month)) %>" data-autotab-format="number"/> /
      <input id="start_day" class="date-field" name="entry[date(3i)]" maxlength="2" placeholder="DD" value="<%= current_date_val(entry.date.try(:day)) %>" data-autotab-format="number" /> /
      <input id="start_year" class="date-field" name="entry[date(1i)]" maxlength="4" placeholder="YYYY" value="<%= current_date_val(entry.date.try(:year)) %>" data-autotab-format="number"/>
    </div> <span class="date-divide">-</span>

    <div id="end_date" class="datefield <%= error_border(entry.errors[:end_date]) %>">
      <input id="end_month" class="date-field" name="entry[end_date(2i)]" maxlength="2" placeholder="MM" value="<%= current_date_val(entry.end_date.try(:month)) %>" data-autotab-format="number"/> /
      <input id="end_day" class="date-field" name="entry[end_date(3i)]" maxlength="2" placeholder="DD" value="<%= current_date_val(entry.end_date.try(:day)) %>" data-autotab-format="number" /> /
      <input id="end_year" class="date-field" name="entry[end_date(1i)]" maxlength="4" placeholder="YYYY" value="<%= current_date_val(entry.end_date.try(:year)) %>" data-autotab-format="number"/>
    </div>
    <br/>
    <span class="month-errors"></span><span class="day-errors"></span><span class="year-errors"></span>
    <%= error_message(entry.errors[:date], 'date') %>
    <%= error_message(entry.errors[:end_date], 'end_date') %>
  </p>

  <p>
    <%= f.label :location, 'Where' %><br>
    <%= f.text_field :location, class: "form-field #{error_border(entry.errors[:location])}", placeholder: 'Where did it happen?' %>
    <%= error_message(entry.errors[:location], 'location') %>
  </p>

  <p>
    <%= f.label :body, 'How' %><br>
    <%= f.text_area :body, class: "form-body form-field #{error_border(entry.errors[:body])}", placeholder: 'How did it happen?' %>
    <%= error_message(entry.errors[:body], 'body') %>
  </p>

  <p>
    <%= f.label :category_list, 'Categories' %><br>
    <%= f.text_field :category_list, id: "select2field", style: "width:100%" %>
  </p>
  
  <div class="modal-footer">
    <%= link_to "Back", entries_path, class: 'cancel-button button link-button' %>
    <%= f.submit 'Save', class: 'button' %>
  </div>

<% end %>

<script>

$(document).ready(function() {
  $("#select2field").select2({
    minimumInputLength: 1,
    tags: <%= raw Category.pluck(:name) %>,
    tokenSeparators: [","]
  });

  $('[data-toggle="tooltip"]').tooltip();
});

</script>

app/views/entries/_timeline.js.erb
var _MS_PER_DAY = 1000 * 60 * 60 * 24;

$(document).ready(function(){
  // set variables
  

  // calculate timeline bar height
  
  
  // set dot heights based on dates


  var entries = <%= raw @entries.to_json %>;
  window.foo = entries
  var firstDate = new Date('<%= @entries.first.date %>');
  var lastDate = new Date('<%= @entries.last.date %>');
  var barHeight = ((yearsDiff(firstDate, lastDate)) * 50) + 100

  document.getElementById('cd-timeline').style.height=barHeight + "px";
 <% if true %> 

  for (var i=0; i < entries.length; i+=1) {
    var entryID = entries[i].id
    var entryDate = new Date(entries[i].date)

    var topOffset = Math.floor((yearsDiff(entryDate, firstDate)) * 50)
    $('#timeline-dot-' + entryID).css('top', topOffset);
    $('#entry-' + entryID).css('top', topOffset);
    
  }
<% end %>
});

function yearsDiff(date1, date2) {
  var utc1 = Date.UTC(date1.getFullYear(), date1.getMonth(), date1.getDate());
  var utc2 = Date.UTC(date2.getFullYear(), date2.getMonth(), date2.getDate());
  return Math.abs((utc2 - utc1) / (_MS_PER_DAY * 365));
}

app/views/entries/_validation.js.erb
function fieldPresent(id, div_class) {
  new_val = $(id).val()
  if (new_val.length == 0) {
    $(id).removeClass("error-border").addClass("error-border");
    $("div." + div_class).remove();
    $(id).after("<div class=" + div_class + ">Sorry, this field cannot be blank!</small>")
  }
  else {
    $(id).removeClass("error-border")
    $("div." + div_class).remove();
  }
}

function validMonth(id, id2, date) {
  month_val = $(id).val()
  month2_val = $(id2).val()

  if ((month_val >= 1 && month_val <= 12) || month_val == "") {
    if ((month2_val >= 1 && month2_val <= 12) || month2_val == "") {
      $(".month-errors").text("")
    }
    $(id).removeClass("error-font")
    $(date).removeClass("month-error-border")
  }
  else {
    $(id).addClass("error-font")
    $(date).addClass("month-error-border")
    $(".month-errors").text("That month is invalid. ")
  }
}

function validDay(id, id2, date, last_day) {
  day_val = $(id).val()
  day_2val = $(id2).val()
  if ((day_val >= 1 && day_val <= last_day) || day_val == "") {
    if ((day_2val >= 1 && day_2val <= last_day) || day_2val == "") {
      $(".day-errors").text("");
    }
    $(id).removeClass("error-font")
    $(date).removeClass("day-error-border")
  }
  else {
    $(id).addClass("error-font")
    $(date).addClass("day-error-border")
    $(".day-errors").text("That day is invalid. ")
  }
}

function validYear(id, id2, date)  {
  year_val = $(id).val()
  year2_val = $(id2).val()
  current_year = new Date().getFullYear() + 100
  if ((year_val >= 1000 && year_val <= current_year) || year_val == "") {
    if ((year2_val >= 1000 && year2_val <= current_year) || year2_val == "") {
      $(".year-errors").text("");
    }
    $(id).removeClass("error-font")
    $(date).removeClass("year-error-border")
  }
  else {
    $(id).addClass("error-font")
    $(date).addClass("year-error-border")
    $(".year-errors").text("That year is invalid. ")
  }
}

function validStartDate() {
  month_val = $('#start_month').val()
  var month_group = ["1", "3", "5", "7", "8", "10", "12"];
  var date = "#start_date"
  validMonth("#start_month", "#end_month", date);
  validYear("#start_year", "#end_year", date);
  if(month_group.indexOf(month_val) > -1) {
    validDay("#start_day", "#end_day", date, 31);
  } else if (month_val == 4 || month_val == 6 || month_val == 9 || month_val == 11) {
    validDay("#start_day", "#end_day", date, 30);
  } else if (month_val == 2) {
    validDay("#start_day", "#end_day", date, 29);
  } else {
    validDay("#start_day", "#end_day", date, 30);
  }
}

function validEndDate() {
  month_val = $('#end_month').val()
  var month_group = ["1", "3", "5", "7", "8", "10", "12"];
  var date = "#end_date"
  validMonth("#end_month", "#start_month", date);
  validYear("#end_year", "#start_year", date);
  if(month_group.indexOf(month_val) > -1) {
    validDay("#end_day", "#start_day", date, 31);
  } else if (month_val == 4 || month_val == 6 || month_val == 9 || month_val == 11) {
    validDay("#end_day", "#start_day", date, 30);
  } else if (month_val == 2) {
    validDay("#end_day", "#start_day", date, 29);
  } else {
    validDay("#end_day", "#start_day", date, 30);
  }
}

// Presence of title
$("#entry_title").blur(function(){
  fieldPresent("#entry_title", "title-error-field")
});

// Presence of start date

$("#start_date").change(function(){
  month_val = $("#start_month").val()
  day_val = $("#start_day").val()
  year_val = $("#start_year").val()
  if ((month_val && day_val && year_val) != "") {
    $(".datefield").removeClass("error-border")
    $("div.date-error-field").remove();
  }
});

$("#end_date").change(function(){
  month_val = $("#end_month").val()
  day_val = $("#end_day").val()
  year_val = $("#end_year").val()
  if ((month_val && day_val && year_val) != "") {
    $(".datefield").removeClass("error-border")
    $("div.end_date-error-field").remove();
  }
});

// Valid start month/day/year

$("#start_month").change(function(){
  validStartDate();
});

$("#start_day").change(function(){
  validStartDate();
});

$("#start_year").change(function(){
  validStartDate();
});

// Valid end month/day/year

$("#end_month").change(function(){
  validEndDate();
});

$("#end_day").change(function(){
  validEndDate();
});

$("#end_year").change(function(){
  validEndDate();
});

// Presence of location

$("#entry_location").blur(function(){
  fieldPresent("#entry_location", "location-error-field")
});

// Presence of body

$("#entry_body").blur(function(){
  fieldPresent("#entry_body", "body-error-field")
});

app/views/entries/create.js.erb
<%= render partial: 'layouts/flash.js' %>
<% if @entry.errors.any? %>
  $('#modal-entry-body').html("<%=j render partial: 'form', locals: { entry: @entry } %>");
  <%= render partial: 'validation.js' %>
  <%= render partial: 'autopopulate.js' %>
<% else %>
  $('#entry_modal').modal('hide');
  $("#timeline-embed").html("");
  $(document).ready(function() {
    createStoryJS({
      type:               'timeline',
      width:              '100%',
      height:             '575',
      source:             "/entries.json?" + $(this).serialize(),
      embed_id:           'timeline-embed',
      start_at_slide:     '<%= @entries.map {|e| e.id }.index(@entry.id) %>',
      css:                '/assets/timeline-new.css',
      js:                 '/timeline-min.js'
    });
  });

<% end %>

app/views/entries/edit.html.erb
<div class="container">
  <div class="row">
    <div class="act-form-box">
      <%= render partial: 'form2', locals: { entry: @entry } %>
    </div>
  </div>
</div>

<script>
  <%= render partial: 'validation.js' %>
  <%= render partial: 'autopopulate.js' %>
</script>

app/views/entries/edit.js.erb
$('#modal-entry-body').html("<%=j render partial: 'form', locals: { entry: @entry } %>");

<%= render partial: 'validation.js' %>
<%= render partial: 'autopopulate.js' %>

app/views/entries/index.html.erb
<div class="timeline-headline"></div>
<div class="container">
  <div class="row">

    <div class='search-box pull-right'>
      <%= form_tag entries_path, method: 'get', id: 'keyword-search' do %>
        <%= text_field_tag :keyword_search, params[:keyword_search], class: 'search-field', placeholder: 'What are you looking for?' %>
        <% end %>
      <%= link_to "Search by date", "#", class: 'date-search-link pull-right' %>
    </div>

    <div class='pull-right date-search-section' style="display: none">
      <%= form_tag entries_path, method: 'get', id: 'date-search' do %>

       <span class="date-search-one date-search-box" id="date-one">
         <input id="date1-month" class="date-field" name="start_date[(2i)]" maxlength="2" placeholder="MM" value="<%#= current_date_val(entry.date.try(:month)) %>" data-autotab-format="number"/> /
         <input id="date1-day" class="date-field" name="start_date[(3i)]" maxlength="2" placeholder="DD" value="<%#= current_date_val(entry.date.try(:day)) %>" data-autotab-format="number" /> /
         <input id="date1-year" class="date-field" name="start_date[(1i)]" maxlength="4" placeholder="YYYY" value="<%#= current_date_val(entry.date.try(:year)) %>" data-autotab-format="number"/> 
       </span>
       <span class="date-text">to</span>

       <span class="date-search-two date-search-box" id="date-two">
         <input id="date2-month" class="date-field" name="end_date[(2i)]" maxlength="2" placeholder="MM" value="<%#= current_date_val(entry.date.try(:month)) %>" data-autotab-format="number"/> /
         <input id="date2-day" class="date-field" name="end_date[(3i)]" maxlength="2" placeholder="DD" value="<%#= current_date_val(entry.date.try(:day)) %>" data-autotab-format="number" /> /
         <input id="date2-year" class="date-field" name="end_date[(1i)]" maxlength="4" placeholder="YYYY" value="<%#= current_date_val(entry.date.try(:year)) %>" data-autotab-format="number"/> 
       </span>
      <% end %><br/>
      <%= link_to "Search by keyword", "#", class: 'keyword-search-link pull-right' %>
    </div>

   
    <% if current_user %>
      <%= link_to '⊕', new_entry_path, class: 'add-entry-icon', "data-toggle" => "modal", 'data-target' => "#entry_modal", remote: :true %>
    <% end %>

    <div class="modal fade" id="entry_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content modal-form">
          <div class="modal-body">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
             <br/>
            <div id="modal-entry-body">

            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade" id="show_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content one-entry">
          <div class="modal-body">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <div id="modal-show-body">

            </div>
          </div>
        </div>
      </div>
    </div>

  </div>

</div>
  <div id="timeline-embed"></div>
  
  <%= javascript_include_tag "/storyjs-embed.js" %>
  <%= javascript_include_tag "/timeline-js", "search" %>

app/views/entries/new.html.erb
<div class="container">
  <div class="row">
    <div class="act-form-box">
      <%= render partial: 'form2', locals: { entry: @entry } %>
    </div>
  </div>
</div>

<script>
  <%= render partial: 'validation.js' %>
  <%= render partial: 'autopopulate.js' %>
</script>

app/views/entries/new.js.erb
$('#modal-entry-body').html("<%=j render partial: 'form', locals: { entry: @entry } %>");

<%= render partial: 'validation.js' %>
<%= render partial: 'autopopulate.js' %>

app/views/entries/update.js.erb
<%= render partial: 'layouts/flash.js' %>

<% if @entry.errors.any? %>
  $('#modal-entry-body').html("<%=j render partial: 'form', locals: { entry: @entry } %>");
  <%= render partial: 'validation.js' %>
  <%= render partial: 'autopopulate.js' %>
<% else %>
  $('#entry_modal').modal('hide');
  $("#timeline-embed").html("");

  $(document).ready(function() {
    createStoryJS({
      type:               'timeline',
      width:              '100%',
      height:             '575',
      source:             "/entries.json?" + $(this).serialize(),
      embed_id:           'timeline-embed',
      start_at_slide:     '<%= @entries.map {|e| e.id }.index(@entry.id) %>',
      css:                '/assets/timeline-new.css',
      js:                 '/timeline-min.js'
    });
  });

<% end %>