config/routes.rb
Rails.application.routes.draw do

  authenticated do
    root to: 'entries#index', as: :authenticated
  end

  root 'home#index'
  get '/home' => 'home#index'
  get '/about' => 'home#about'
  get '/contact' => 'home#contact'

  devise_for :users

  resources :entries
  resources :categories, param: :name

  post "/scraper" => "scrapers#create"
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :categorizings
	has_many :entries, through: :categorizings

	def to_s
		name
	end

	def to_param
		name
	end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def index
		@categories = Category.all
	end

	def show
		@category = Category.find_by_name(params[:name])
		@entries = @category.entries
	end

	def destroy
		@category = Category.find_by_name(params[:name])
		@category.destroy
		redirect_to categories_path
	end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_sidebar.html.erb
<div class="sidebar">
  <h4 class="sidebar_header">Categories</h4>
  <% @categories.each do |category| %>
    <% if category.entries.size > 0 %>
      <div><%= link_to "#{category.name} (#{category.entries.size})", category_path(category) %></div>
    <% end %>
  <% end %>
</div>

app/views/categories/index.html.erb
<div class="container">

<div class="row">
  <h2>Categories</h2>

  <div class="categories">
		<% @categories.each do |category| %>
			<div>
				<%= link_to "#{category.name} (#{category.entries.size})", category_path(category) %> 

        <% if current_user %>
  				<small>
            <%= link_to "✖", category_path(category), method: :delete, data: {confirm: "Are you sure?"} %>
          </small>
        <% end %>
        
			</div>
		<% end %>
  </div>
</div>

<div class="row"><%= link_to 'All entries', entries_path, class: 'login-link' %></div>
</div><br/>

app/views/categories/show.html.erb
<h2><em><%= @category.name %></em> category</h2></br>

  <div class="modal fade" id="entry_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content modal-form">
        <div class="modal-body">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
           <br/>
          <div id="modal-entry-body">

          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="show_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content one-entry">
        <div class="modal-body">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <div id="modal-show-body">

          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="entries_index">
    <%= render partial: 'entries/entry', collection: @entries %>
  </div>

<%= link_to "All entries", entries_path %>